spring:
  mustache:
    servlet:
      expose-session-attributes: 'true'
      cache: 'false'
    suffix: .html
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '1234'
    url: jdbc:mysql://localhost:3306/spring_cafe?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
  sql:
    init:
      mode: always
server:
  servlet:
    encoding:
      force-response: 'true'
